language: node_js

dist: trusty

cache:
  directories:
    - node_modules

before_install:
  - npm install -g angular-cli

install:
  - npm install

script:
  - ng test --browsers Chrome_no_sandbox -w false

notifications:
  email:
    on_success: never
    on_failure: change


